type Query {
  getProductById(productId: ID!): Product
  getShoppingCartById(shoppingCartId: ID!): ShoppingCart
}
type Mutation {
  createShoppingCart: ShoppingCart
  addItemToShoppingCart(input: ShoppingInputIds): ShoppingCart
  removeItemFromShoppingCart(input: ShoppingInputIds): ShoppingCart
  deleteShoppingCart(shoppingCartId: ID!): DeleteResourceResponse
}

type DeleteResourceResponse {
  deletedId: ID
  success: Boolean
}
type ShoppingCart {
  shoppingCartId: ID
  shoppingCartItems: [ShoppingCartItem]
  totalPrice: Float
}
type Product {
  productId: ID
  productName: String
  unitPrice: Float
}
type ShoppingCartItem {
  productId: ID
  productName: String
  unitPrice: Float
  quantity: Int
}
input ShoppingInputIds {
  productId: ID!
  shoppingCartId: ID!
}
